abstract: A Catalyst interface to the Jifty db layer
author: Marcus Ramberg, <mramberg@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Catalyst-Model-Jifty-DBI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.64
  Jifty::DBI: 0
version: 0.01
