--- #YAML:1.0
name:                Catalyst-Model-Jifty-DBI
version:             0.04
abstract:            Jifty::DBI Model Class with some magic on top
license:             perl
author:              
    - Kenichi Ishigaki <ishigaki@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Catalyst::Runtime:             0
    Class::Accessor::Fast:         0
    File::Basename:                0
    File::Spec:                    0
    Jifty::DBI:                    0.47
    Module::Find:                  0
    NEXT:                          0
    Test::UseAllModules:           0.09
    UNIVERSAL::require:            0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
