--- #YAML:1.0
name:                Catalyst-Model-Jifty-DBI
version:             0.03
abstract:            Jifty::DBI Model Class with some magic on top
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Catalyst::Runtime:             0
    Class::Accessor::Fast:         0
    File::Basename:                0
    File::Spec:                    0
    Jifty::DBI:                    0.47
    Module::Find:                  0
    NEXT:                          0
    Test::UseAllModules:           0
    UNIVERSAL::require:            0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
